WITH RECURSIVE TIME AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1 FROM TIME WHERE HOUR <23
)

SELECT HOUR, IFNULL(A.COUNT, 0)
FROM TIME LEFT JOIN (
    SELECT HOUR(DATETIME) AS HOUR, IFNULL(COUNT(ANIMAL_ID), 0) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR(DATETIME)
) AS A
USING (HOUR)